# Generated by Django 4.2.10 on 2024-03-07 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Course name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle name')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('date_enroll', models.DateField(verbose_name='Date of enrollment')),
                ('payer', models.BooleanField(verbose_name='Contractor')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('language', models.CharField(max_length=255, verbose_name='Language')),
                ('form_of_study', models.CharField(choices=[('Очно', 'Очно'), ('Заочно', 'Заочно')], max_length=255, verbose_name='Form of study')),
                ('contract_date', models.DateField(verbose_name='Contract date')),
                ('contract_id', models.CharField(max_length=255, verbose_name='Contract id')),
                ('contract_price', models.CharField(max_length=255, verbose_name='Contract price')),
                ('discount', models.CharField(blank=True, max_length=255, null=True, verbose_name='Discount')),
                ('promotion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Promotion')),
                ('find_out', models.CharField(blank=True, max_length=255, null=True, verbose_name='Where found out')),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Agent name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_app.course', verbose_name='Course')),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle name')),
                ('personal_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal ID')),
                ('representative_type', models.CharField(blank=True, choices=[('Отец', 'Отец'), ('Мать', 'Мать'), ('Представитель', 'Представитель')], max_length=255, null=True, verbose_name='Representative type')),
                ('payer', models.BooleanField(verbose_name='Contractor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_app.student', verbose_name='Student')),
            ],
        ),
    ]
