# Generated by Django 4.2.10 on 2024-03-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_rename_child_representative_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-created_at',)},
        ),
    ]
