# Generated by Django 4.2.10 on 2024-03-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course price'),
        ),
        migrations.AddField(
            model_name='representative',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='representative',
            name='other_contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other contact'),
        ),
        migrations.AddField(
            model_name='representative',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='student',
            name='debtor',
            field=models.BooleanField(default=False, verbose_name='Debtor'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='other_contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other contact'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone'),
        ),
    ]
