# Generated by Django 4.2.10 on 2024-03-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_course_price_representative_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='personal_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal ID'),
        ),
    ]
