# Generated by Django 4.2.10 on 2024-03-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0007_remove_student_residence_permit_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='residence_permit_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Residence Permit End Date'),
        ),
    ]
