# Generated by Django 4.2.10 on 2024-03-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0009_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='representative',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='representative',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
    ]
