# Generated by Django 4.2.10 on 2024-04-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0010_representative_address_representative_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
