# Generated by Django 4.2.10 on 2024-04-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0011_remove_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('grade', models.CharField(max_length=255, verbose_name='Grade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_app.course', verbose_name='Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_app.student', verbose_name='Student')),
            ],
        ),
    ]
