# Generated by Django 4.2.10 on 2024-04-10 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0013_course_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Subject name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='student',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contract_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contract_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contract_price',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_enroll',
        ),
        migrations.RemoveField(
            model_name='student',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='student',
            name='find_out',
        ),
        migrations.RemoveField(
            model_name='student',
            name='form_of_study',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='student',
            name='promotion',
        ),
        migrations.AddField(
            model_name='representative',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AddField(
            model_name='representative',
            name='personal_id_details',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal ID details'),
        ),
        migrations.AddField(
            model_name='student',
            name='personal_id_details',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal ID details'),
        ),
        migrations.AddField(
            model_name='student',
            name='residence_permit_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Residence Permit Active'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Phone'),
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle name')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('personal_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal ID')),
                ('personal_id_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal ID details')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('representative_type', models.CharField(blank=True, choices=[('Отец', 'Отец'), ('Мать', 'Мать'), ('Представитель', 'Представитель')], max_length=255, null=True, verbose_name='Representative type')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('other_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Other contact')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_app.student', verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_of_study', models.CharField(blank=True, max_length=255, null=True, verbose_name='Form of study')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('contract_date', models.DateField(verbose_name='Contract date')),
                ('contract_id', models.CharField(max_length=255, verbose_name='Contract ID')),
                ('contract_price', models.FloatField(verbose_name='Contract Price')),
                ('pay_date', models.DateField(verbose_name='Pay date')),
                ('installment_plan', models.BooleanField(verbose_name='Installment Plan')),
                ('discount', models.CharField(blank=True, max_length=255, null=True, verbose_name='Discount')),
                ('promotion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Promotion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_app.contractor', verbose_name='Contractor')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_app.course', verbose_name='Course')),
            ],
        ),
    ]
