# Generated by Django 4.2.10 on 2024-04-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0016_alter_student_email_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone'),
        ),
    ]
