# Generated by Django 4.2.10 on 2024-04-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0017_alter_student_email_alter_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.FloatField(verbose_name='Amount')),
                ('pay_date', models.DateField(verbose_name='Pay date')),
                ('payed', models.BooleanField(verbose_name='Payed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_app.contract', verbose_name='Contract')),
            ],
        ),
    ]
