# Generated by Django 4.2.10 on 2024-04-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0018_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='residence_permit_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='residence_permit_end_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='residence_permit_id',
        ),
        migrations.AlterField(
            model_name='contract',
            name='form_of_study',
            field=models.CharField(blank=True, choices=[('Очно', 'Очно'), ('Заочно', 'Заочно')], max_length=255, null=True, verbose_name='Form of study'),
        ),
    ]
