# Generated by Django 4.2.10 on 2024-04-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0019_remove_student_residence_permit_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Internship name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('result', models.CharField(max_length=255, verbose_name='Result')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_app.student', verbose_name='Student')),
            ],
        ),
    ]
