# Generated by Django 4.2.10 on 2024-04-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0021_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence_permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(verbose_name='Arrival Date')),
                ('student_visa', models.BooleanField(verbose_name='Student visa')),
                ('registration_address', models.CharField(max_length=255, verbose_name='Registration address')),
                ('residence_permit_id', models.CharField(max_length=255, verbose_name='Residence permit ID')),
                ('residence_permit_issue_date', models.DateField(verbose_name='Residence permit issue date')),
                ('residence_permit_end_date', models.DateField(verbose_name='Residence permit end date')),
                ('residence_permit_type', models.CharField(max_length=255, verbose_name='Residence permit type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_app.student', verbose_name='Student')),
            ],
        ),
    ]
