# Generated by Django 4.2.10 on 2024-04-18 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0023_statement_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject of Application')),
                ('date_issued', models.DateField(verbose_name='Issue Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_app.student', verbose_name='Student')),
            ],
        ),
    ]
