# Generated by Django 4.2.10 on 2024-04-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0024_alter_statement_name_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='student',
            field=models.ManyToManyField(to='site_app.student', verbose_name='Student'),
        ),
    ]
