# Generated by Django 4.2.10 on 2024-04-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0028_remove_contract_course_contract_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='site_app.course', verbose_name='Course'),
        ),
    ]
