# Generated by Django 4.2.10 on 2024-04-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0030_remove_contract_course_remove_contract_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='student',
        ),
    ]
