# Generated by Django 4.2.10 on 2024-04-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0031_remove_contractor_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='contractor',
            field=models.BooleanField(blank=True, null=True, verbose_name='Contractor'),
        ),
    ]
