# Generated by Django 4.2.10 on 2024-04-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0033_alter_contract_contractor_delete_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='student',
            name='form_of_study',
            field=models.CharField(blank=True, choices=[('Очно', 'Очно'), ('Заочно', 'Заочно')], max_length=255, null=True, verbose_name='Form of study'),
        ),
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
