# Generated by Django 4.2.10 on 2024-04-29 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0037_remove_student_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Student', to='site_app.student', verbose_name='Photo'),
        ),
    ]
