# Generated by Django 4.2.10 on 2024-04-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0038_alter_photo_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_app.student', verbose_name='Student'),
        ),
    ]
