# Generated by Django 4.2.10 on 2024-05-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0041_alter_representative_representative_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
    ]
