# Generated by Django 4.2.10 on 2024-05-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0042_remove_grade_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Language'),
        ),
    ]
