# Generated by Django 4.2.10 on 2024-05-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0043_representative_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='form_of_study',
            field=models.CharField(choices=[('In Person', 'In Person'), ('Distance', 'Distance')], max_length=255, verbose_name='Form of study'),
        ),
        migrations.AlterField(
            model_name='student',
            name='personal_id',
            field=models.CharField(max_length=255, verbose_name='Personal ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='personal_id_details',
            field=models.CharField(max_length=255, verbose_name='Personal ID details'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
    ]
