# Generated by Django 4.2.10 on 2024-05-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0044_alter_student_address_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='birth_date',
            field=models.DateField(verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='contractor',
            field=models.BooleanField(verbose_name='Contractor'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='language',
            field=models.CharField(max_length=255, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='personal_id',
            field=models.CharField(max_length=255, verbose_name='Personal ID'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='personal_id_details',
            field=models.CharField(max_length=255, verbose_name='Personal ID details'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='representative_type',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Representative', 'Representative')], max_length=255, verbose_name='Representative type'),
        ),
    ]
