# Generated by Django 4.2.10 on 2024-05-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0045_alter_representative_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=' ', max_length=255, verbose_name='Order ID'),
        ),
    ]
